services:
  web:
    build: .
    domain: ${DOMAIN}
    environment:
      - ALGOLIA_APP=
      - ALGOLIA_INDEX=
      - ALGOLIA_KEY_ADMIN=
      - ALGOLIA_KEY_SEARCH=
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - BUCKET
    health:
      path: /check
      interval: 5
    init: true
    port: https:3000
